### ISSUE TITLE
我是个学生，可以发布一下镜像吗？

### ISSUE THREAD

**Issue by trytocatchyou** [ChangSZ/blog#1]
![image](https://github.com/ChangSZ/blog/assets/31500424/4f81ece0-d362-45d4-84b6-85e2aadacbe8)

**Comment by ChangSZ** [comment]
可以呀，我这没限制的

> ![image](https://user-images.githubusercontent.com/31500424/279592174-4f81ece0-d362-45d4-84b6-85e2aadacbe8.png)
